version: '2'
services:
## Jenkins
  jenkins:
    image: 'jenkins/jenkins'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami'
## sonarqube
  sonarqube:
    image: sonarqube:6.7.1
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=password1
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db-sonar:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
## sonar database
  db-sonar:
    image: postgres:latest
    container_name: db-sonar
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=sonarqube
    ports: 
      - "15431:5432"
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/po stgresql/data
## gitlab
  git-lab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    #hostname: "gitlab.example.com"
    environment:
      GITLAB_OMNIBUS_CONFIG:  | 
        prometheus_monitoring['enable'] = false; 
        gitlab_rails['initial_root_password'] = 'password'
      #GITLAB_OMNIBUS_CONFIG: |
        #external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "82:80"
      - "445:443"
      - "2222:22"
    volumes:
      - "./srv/gitlab/config:/etc/gitlab"
      - "./srv/gitlab/logs:/var/log/gitlab"
      - "./srv/gitlab/data:/var/opt/gitlab"
 
  ## ELK
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.2
    container_name: kibana
    environment: 
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports: 
      - 5601:5601
    depends_on: 
      - elasticsearch
  nexus:
    image: sonatype/nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8081:8081"
  jira:
    image: addteq/jira:latest
    container_name: demo-jira-latest
    ports: 
      - 8080:8080
    volumes:
      - ./jira-home:/opt/atlassian-home
  compodoc:
    image: zalari/compodoc-ngrx
    container_name: compodoc
    ports: 
      - 8085:8085

networks:
  esnet:


volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
  nexus-data: {}
  esdata1:
      driver: local

  jenkins_data:
    driver: local
